In [75]:
import torch
import numpy as np

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [3]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

#--------------------------------------------

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.7610, 0.2816],
        [0.2496, 0.0397]]) 



In [4]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.6496, 0.1494, 0.2192],
        [0.6194, 0.7864, 0.3071]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [5]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")
tensor

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


tensor([[0.4929, 0.3550, 0.3668, 0.2424],
        [0.1689, 0.6732, 0.4851, 0.0797],
        [0.2063, 0.1202, 0.5667, 0.9553]])

# Test of tensor environment Done:
---

# chapter 1:
---



In [56]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print('useful')
else:
    print("shit")

shit


In [7]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0 #slicing change
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


## col & row bind dataframe


In [8]:
t1 = torch.cat([tensor, tensor, tensor], dim=0) #be 1 to col bind
print(t1)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


## number manipulation


In [9]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)
#--------------------------------------------
tensor.t_() #转置

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


tensor([[6., 6., 6., 6.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])

## tensor to Numpy array


In [13]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [13]:
n = np.ones(5)
t = torch.from_numpy(n)
print(t)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [14]:
np.add(n, 2, out=n)
print(f"t: {t}")
print(f"n: {n}")

mm = "---------"

t: tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
n: [3. 3. 3. 3. 3.]


# np quick review.

In [15]:
np.full((2,3),7)
print(f"{mm} this is a line to seperate: {mm} \n")

print(np.arange(10,25,5)) # start end, step length

print(f"{mm} this is a line to seperate: {mm} \n")

print(np.linspace(0,2,6)) # start end, num of list

print(f"{mm} this is a line to seperate: {mm} \n")
a =np.random.random((2,3))

#--------------------------------------------
 # fancy indexing:
# a[[x],[y]] #(element located at x,y)


--------- this is a line to seperate: --------- 

[10 15 20]
--------- this is a line to seperate: --------- 

[0.  0.4 0.8 1.2 1.6 2. ]
--------- this is a line to seperate: --------- 



In [16]:
a

array([[0.05229041, 0.59799725, 0.36725583],
       [0.39336756, 0.76518238, 0.26444152]])

In [17]:
a[:,2], a[::-1]# upside down
print(np.transpose(a)) # tranpose
a.ravel() # one line
a.reshape(-1,1)

[[0.05229041 0.39336756]
 [0.59799725 0.76518238]
 [0.36725583 0.26444152]]


array([[0.05229041],
       [0.59799725],
       [0.36725583],
       [0.39336756],
       [0.76518238],
       [0.26444152]])

In [18]:
a[[1],[1]]

array([0.76518238])

In [19]:
b = np.append(a,a)
# b.shape #(12,)
c = np.concatenate((a,a), axis = 0)
c.shape #(4, 3)
d = np.concatenate((a,a), axis = 1)
d.shape #(2, 6)
e = np.vstack((a,a))  # ==~ c
f = np.hstack((a,a))  # ==~ d

# np.r_[a,a] ; np.c_[a,a]

In [20]:
a, b, c, d, e, f
# b.size ,b.resize(())

(array([[0.05229041, 0.59799725, 0.36725583],
        [0.39336756, 0.76518238, 0.26444152]]),
 array([0.05229041, 0.59799725, 0.36725583, 0.39336756, 0.76518238,
        0.26444152, 0.05229041, 0.59799725, 0.36725583, 0.39336756,
        0.76518238, 0.26444152]),
 array([[0.05229041, 0.59799725, 0.36725583],
        [0.39336756, 0.76518238, 0.26444152],
        [0.05229041, 0.59799725, 0.36725583],
        [0.39336756, 0.76518238, 0.26444152]]),
 array([[0.05229041, 0.59799725, 0.36725583, 0.05229041, 0.59799725,
         0.36725583],
        [0.39336756, 0.76518238, 0.26444152, 0.39336756, 0.76518238,
         0.26444152]]),
 array([[0.05229041, 0.59799725, 0.36725583],
        [0.39336756, 0.76518238, 0.26444152],
        [0.05229041, 0.59799725, 0.36725583],
        [0.39336756, 0.76518238, 0.26444152]]),
 array([[0.05229041, 0.59799725, 0.36725583, 0.05229041, 0.59799725,
         0.36725583],
        [0.39336756, 0.76518238, 0.26444152, 0.39336756, 0.76518238,
         0.26444152]

In [21]:
np.delete(a, ([2],[3])) #delete [2] and [3]
# np.delete(a, [[2],[3]])


array([0.05229041, 0.59799725, 0.76518238, 0.26444152])

In [22]:
np.hsplit(a,3), np.vsplit(a,2)# every 3rd index

([array([[0.05229041],
         [0.39336756]]),
  array([[0.59799725],
         [0.76518238]]),
  array([[0.36725583],
         [0.26444152]])],
 [array([[0.05229041, 0.59799725, 0.36725583]]),
  array([[0.39336756, 0.76518238, 0.26444152]])])

---

In [23]:
import pickle
with open('train.pickle', 'wb') as f:
    pickle.dump([a, mm], f)

In [24]:
with open('train.pickle', 'rb') as f:
    a, mm = pickle.load(f)

## quick review on pandas

In [6]:
import pandas as pd


In [25]:
cc = pd.DataFrame(c)

In [26]:
cc = cc.rename(index = str,
          columns= {0:"c1",
                    1:"c2",
                    2:"c3"})

In [31]:
cc['c4'] = ['a','b','c','d']
cc['row'] = np.arange(1,5)

In [ ]:
cc

In [70]:
cc.pivot(index = 'row', columns= 'c4',
         values = ['c1', 'c2', 'c3'])
pd.pivot_table(cc, index = 'row', columns= 'c4',
         values = ['c1', 'c2', 'c3'])

c1                                     c2                      \
c4         a         b        c         d         a         b         c   
row                                                                       
1    0.05229       NaN      NaN       NaN  0.597997       NaN       NaN   
2        NaN  0.393368      NaN       NaN       NaN  0.765182       NaN   
3        NaN       NaN  0.05229       NaN       NaN       NaN  0.597997   
4        NaN       NaN      NaN  0.393368       NaN       NaN       NaN   

                     c3                                
c4          d         a         b         c         d  
row                                                    
1         NaN  0.367256       NaN       NaN       NaN  
2         NaN       NaN  0.264442       NaN       NaN  
3         NaN       NaN       NaN  0.367256       NaN  
4    0.765182       NaN       NaN       NaN  0.264442

In [87]:
ccm = pd.melt(cc,
        id_vars = ["c4"],
        value_vars = ["c1", "c2", "c3"],
        value_name = "test")
ccm

c1        c2        c3 c4  row
0  0.052290  0.597997  0.367256  a    1
1  0.393368  0.765182  0.264442  b    2
2  0.052290  0.597997  0.367256  c    3
3  0.393368  0.765182  0.264442  d    4

In [95]:
ccm.groupby(by = 'variable').sum()

test
variable          
c1        0.891316
c2        2.726359
c3        1.263395

In [132]:
cc, cc.round(2)

(         c1        c2        c3 c4  row
 0  0.052290  0.597997  0.367256  a    1
 1  0.393368  0.765182  0.777777  b    2
 2  0.052290  0.597997  0.777777  c    3
 3  0.393368  0.765182  0.264442  d    4,
      c1    c2    c3 c4  row
 0  0.05  0.60  0.37  a    1
 1  0.39  0.77  0.78  b    2
 2  0.05  0.60  0.78  c    3
 3  0.39  0.77  0.26  d    4)

In [106]:
cc.iloc[:, 1], cc.loc['1':'3'] # by position or by row names

0    0.597997
1    0.765182
2    0.597997
3    0.765182
Name: c2, dtype: float64

In [118]:
cc.loc[(cc['c1'] > .06), :]

c1        c2        c3 c4  row
1  0.393368  0.765182  0.264442  b    2
3  0.393368  0.765182  0.264442  d    4

In [166]:
cc.loc[['2', '1'], 'c3'] = 0.777777
cc

c1        c2        c3 c4  row
0  0.052290  0.597997  0.367256  a    1
1  0.393368  0.765182  0.777777  b    2
2  0.052290  0.597997  0.777777  c    3
3  0.393368  0.765182  0.264442  d    4

In [147]:
cc.where(cc['c3'] > .7).dropna()

c1        c2        c3 c4  row
1  0.393368  0.765182  0.777777  b  2.0
2  0.052290  0.597997  0.777777  c  3.0

In [164]:
cc.filter(items=['c1', 'c2']) #select by col


c1        c2
0  0.052290  0.597997
1  0.393368  0.765182
2  0.052290  0.597997
3  0.393368  0.765182

In [165]:
cc.filter(items = ['1','2'], axis = 0) #select by row

c1        c2        c3 c4  row
1  0.393368  0.765182  0.777777  b    2
2  0.052290  0.597997  0.777777  c    3

In [200]:
cc.reindex(['1','2','3', '0']) # 换一下row之间的position


c1        c2        c3 c4  row
1  0.393368  0.765182  0.777777  b    2
2  0.052290  0.597997  0.777777  c    3
3  0.393368  0.765182  0.264442  d    4
0  0.052290  0.597997  0.367256  a    1

In [214]:
cc['c3'].unique()

array([0.36725583, 0.777777  , 0.26444152])

In [215]:
cc.where(cc.duplicated('c3') == True)


c1        c2        c3   c4  row
0      NaN       NaN       NaN  NaN  NaN
1      NaN       NaN       NaN  NaN  NaN
2  0.05229  0.597997  0.777777    c  3.0
3      NaN       NaN       NaN  NaN  NaN

In [262]:
cc.loc[['3'],['c4']] = "d"
cc.iloc[2,3] = 'd'

In [ ]:
cc.groupby('c4').agg({
    'c1': lambda x:sum(x)/len(x),
    'c2': np.mean
})

In [ ]:
cc

In [236]:
# pd.merge(data1, data2,
#          how = 'left',
#          on = 'X1')

#inner , outer # 取两个dataframe的交集和并集


# 或者
# data1.join(data2, how = '')

# 或者
# pd.concat([data1, data2], axis = 1, join = '')


c1        c2        c3 c4  row
0  0.052290  0.597997  0.367256  a    1
1  0.393368  0.765182  0.777777  b    2
2  0.052290  0.597997  0.777777  c    3
3  0.393368  0.765182  0.264442  d    4

In [258]:
cc.replace('a', 'f') # 自动检查并替换
