In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [3]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

#--------------------------------------------

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8335, 0.3885],
        [0.6733, 0.3494]]) 



In [4]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0597, 0.2552, 0.2868],
        [0.4267, 0.0414, 0.9118]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [5]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")
tensor

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


tensor([[0.4929, 0.3550, 0.3668, 0.2424],
        [0.1689, 0.6732, 0.4851, 0.0797],
        [0.2063, 0.1202, 0.5667, 0.9553]])

# Test of tensor environment Done:
---

# chapter 1:
---



In [56]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print('useful')
else:
    print("shit")

shit


In [7]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0 #slicing change
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


## col & row bind dataframe


In [8]:
t1 = torch.cat([tensor, tensor, tensor], dim=0) #be 1 to col bind
print(t1)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


## number manipulation


In [9]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)
#--------------------------------------------
tensor.t_() #转置

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


tensor([[6., 6., 6., 6.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])

## tensor to Numpy array


In [10]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [4]:
n = np.ones(5)
t = torch.from_numpy(n)
print(t)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [5]:
np.add(n, 2, out=n)
print(f"t: {t}")
print(f"n: {n}")

mm = "---------"

t: tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
n: [3. 3. 3. 3. 3.]


# some np quick review.

In [8]:
np.full((2,3),7)
print(f"{mm} this is a line to seperate: {mm} \n")

print(np.arange(10,25,5)) # start end, step length

print(f"{mm} this is a line to seperate: {mm} \n")

print(np.linspace(0,2,6)) # start end, num of list

print(f"{mm} this is a line to seperate: {mm} \n")
a =np.random.random((2,3))

#--------------------------------------------
 # fancy indexing:
# a[[x],[y]] #(element located at x,y)


--------- this is a line to seperate: --------- 

[10 15 20]
--------- this is a line to seperate: --------- 

[0.  0.4 0.8 1.2 1.6 2. ]
--------- this is a line to seperate: --------- 



In [50]:
a

array([[0.92462364, 0.82513807, 0.8430944 ],
       [0.16765532, 0.21691756, 0.1863011 ]])

In [52]:
a[:,2], a[::-1]# upside down
print(np.transpose(a)) # tranpose
a.ravel() # one line
a.reshape(-1,1)

[[0.92462364 0.16765532]
 [0.82513807 0.21691756]
 [0.8430944  0.1863011 ]]


array([[0.92462364],
       [0.82513807],
       [0.8430944 ],
       [0.16765532],
       [0.21691756],
       [0.1863011 ]])

In [11]:
a[[1],[1]]

array([0.21691756])

In [48]:
b = np.append(a,a)
# b.shape #(12,)
c = np.concatenate((a,a), axis = 0)
c.shape #(4, 3)
d = np.concatenate((a,a), axis = 1)
d.shape #(2, 6)
e = np.vstack((a,a))  # ==~ c
f = np.hstack((a,a))  # ==~ d

# np.r_[a,a] ; np.c_[a,a]

In [49]:
a, b, c, d, e, f
# b.size ,b.resize(())

(array([[0.92462364, 0.82513807, 0.8430944 ],
        [0.16765532, 0.21691756, 0.1863011 ]]),
 array([0.92462364, 0.82513807, 0.8430944 , 0.16765532, 0.21691756,
        0.1863011 , 0.92462364, 0.82513807, 0.8430944 , 0.16765532,
        0.21691756, 0.1863011 ]),
 array([[0.92462364, 0.82513807, 0.8430944 ],
        [0.16765532, 0.21691756, 0.1863011 ],
        [0.92462364, 0.82513807, 0.8430944 ],
        [0.16765532, 0.21691756, 0.1863011 ]]),
 array([[0.92462364, 0.82513807, 0.8430944 , 0.92462364, 0.82513807,
         0.8430944 ],
        [0.16765532, 0.21691756, 0.1863011 , 0.16765532, 0.21691756,
         0.1863011 ]]),
 array([[0.92462364, 0.82513807, 0.8430944 ],
        [0.16765532, 0.21691756, 0.1863011 ],
        [0.92462364, 0.82513807, 0.8430944 ],
        [0.16765532, 0.21691756, 0.1863011 ]]),
 array([[0.92462364, 0.82513807, 0.8430944 , 0.92462364, 0.82513807,
         0.8430944 ],
        [0.16765532, 0.21691756, 0.1863011 , 0.16765532, 0.21691756,
         0.1863011 ]

In [23]:
np.delete(a, ([2],[3])) #delete [2] and [3]
# np.delete(a, [[2],[3]])


array([0.92462364, 0.82513807, 0.21691756, 0.1863011 ])

In [55]:
np.hsplit(a,3), np.vsplit(a,2)# every 3rd index

([array([[0.92462364],
         [0.16765532]]),
  array([[0.82513807],
         [0.21691756]]),
  array([[0.8430944],
         [0.1863011]])],
 [array([[0.92462364, 0.82513807, 0.8430944 ]]),
  array([[0.16765532, 0.21691756, 0.1863011 ]])])

---

## quick review on pandas

In [64]:
import pandas as pd


AttributeError: module 'pandas' has no attribute 'dataframe'

In [66]:
cc = pd.DataFrame(c)

In [74]:
cc = cc.rename(index = str,
          columns= {0:"c1",
                    1:"c2",
                    2:"c3"})

In [75]:
cc

c1        c2        c3
0  0.924624  0.825138  0.843094
1  0.167655  0.216918  0.186301
2  0.924624  0.825138  0.843094
3  0.167655  0.216918  0.186301

In [77]:
pd.rename?

Object `pd.rename` not found.
