In [1]:
import torch
import numpy as np

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

In [3]:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

#--------------------------------------------

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor: 
 tensor([[0.8335, 0.3885],
        [0.6733, 0.3494]]) 



In [4]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor}")

Random Tensor: 
 tensor([[0.0597, 0.2552, 0.2868],
        [0.4267, 0.0414, 0.9118]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [5]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")
tensor

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


tensor([[0.4929, 0.3550, 0.3668, 0.2424],
        [0.1689, 0.6732, 0.4851, 0.0797],
        [0.2063, 0.1202, 0.5667, 0.9553]])

# Test of tensor environment Done:
---

# chapter 1:
---



In [6]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')
  print('useful')

In [7]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0 #slicing change
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


## col & row bind dataframe


In [8]:
t1 = torch.cat([tensor, tensor, tensor], dim=0) #be 1 to col bind
print(t1)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


## number manipulation


In [9]:
print(tensor, "\n")
tensor.add_(5)
print(tensor)
#--------------------------------------------
tensor.t_() #转置

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


tensor([[6., 6., 6., 6.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])

## tensor to Numpy array


In [10]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]
t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [11]:
n = np.ones(5)
t = torch.from_numpy(n)
print(t)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [12]:
np.add(n, 2, out=n)
print(f"t: {t}")
print(f"n: {n}")

mm = "---------"

t: tensor([3., 3., 3., 3., 3.], dtype=torch.float64)
n: [3. 3. 3. 3. 3.]


# some np quick review.

In [13]:
np.full((2,3),7)
print(f"{mm} this is a line to seperate: {mm} \n")

print(np.arange(10,25,5)) # start end, step length

print(f"{mm} this is a line to seperate: {mm} \n")
print(np.linspace(0,2,6)) # start end, num of list
print(f"{mm} this is a line to seperate: {mm} \n")
a =np.random.random((2,3))

#--------------------------------------------
 # fancy indexing:
a[[x],[y]] #(element located at x,y)


--------- this is a line to seperate: --------- 

[10 15 20]
--------- this is a line to seperate: --------- 

[0.  0.4 0.8 1.2 1.6 2. ]
--------- this is a line to seperate: --------- 



NameError: name 'x' is not defined

In [14]:
a

array([[0.92794763, 0.60326629, 0.23937314],
       [0.05327643, 0.10958244, 0.79509648]])

In [15]:
a[:,2], a[::-1]# upside down
print(np.transpose(a)) # tranpose
a.ravel()
a.reshape()

[[0.92794763 0.05327643]
 [0.60326629 0.10958244]
 [0.23937314 0.79509648]]


TypeError: reshape() takes exactly 1 argument (0 given)

In [59]:
a[[1],[1]]

array([0.50009298])

In [16]:
b = np.append(a,a)
b.shape #(12,)

(12,)

In [19]:
# b.size ,b.resize(())

---
